In [11]:
# imported numpy and OpenCV
import numpy as np
import cv2 

In [12]:
# imported insightface for face detection and facial feature extraction
import insightface

### how to configure insightface model

In [13]:
from insightface.app import FaceAnalysis

In [14]:
# buffalo_l model
app_l = FaceAnalysis(name='buffalo_l',
                    root = 'insightface_model')
#providers = ['CPUExecutionProvider']
app_l.prepare(ctx_id=0,det_size=(640,640))

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: insightface_model\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: insightface_model\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: insightface_model\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: insightface_model\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: insightface_model\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)


In [5]:
# buffalo_ sc model
app_sc = FaceAnalysis(name='buffalo_sc',
                    root = 'insightface_model')
                    
#providers = ['CPUExecutionProvider']
app_sc.prepare(ctx_id=0,det_size=(640,640))

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: insightface_model\models\buffalo_sc\det_500m.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: insightface_model\models\buffalo_sc\w600k_mbf.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)


In [6]:
img = cv2.imread("im2.jpg")
print(img)

[[[186 205 213]
  [186 205 213]
  [186 205 213]
  ...
  [ 69 109 174]
  [ 77 115 179]
  [ 77 115 179]]

 [[186 205 213]
  [186 205 213]
  [186 205 213]
  ...
  [ 70 110 175]
  [ 78 116 180]
  [ 78 116 180]]

 [[186 205 213]
  [186 205 213]
  [186 205 213]
  ...
  [ 70 110 175]
  [ 79 117 181]
  [ 79 117 181]]

 ...

 [[171 188 197]
  [174 191 200]
  [177 194 203]
  ...
  [184 198 204]
  [188 199 207]
  [188 199 207]]

 [[168 185 194]
  [172 189 198]
  [177 194 203]
  ...
  [182 196 202]
  [186 197 205]
  [186 197 205]]

 [[165 182 191]
  [171 188 197]
  [176 193 202]
  ...
  [181 195 201]
  [185 196 204]
  [185 196 204]]]


In [7]:
img.shape

(1599, 722, 3)

## Load Image

In [7]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### apply image to insight face model and get result

In [8]:
results_l = app_l.get(img)

e:\FASP\attendance_system\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


In [9]:
print(results_l)

[{'bbox': array([182.32878, 314.42258, 286.0953 , 451.79904], dtype=float32), 'kps': array([[203.29437, 371.6302 ],
       [248.44739, 362.32407],
       [226.16486, 394.25845],
       [214.63379, 414.3428 ],
       [257.434  , 406.71124]], dtype=float32), 'det_score': 0.8759457, 'landmark_3d_68': array([[ 1.8528746e+02,  3.7958731e+02,  8.6468643e+01],
       [ 1.8967569e+02,  3.9333044e+02,  8.2516083e+01],
       [ 1.9364845e+02,  4.0749335e+02,  7.7477623e+01],
       [ 1.9815933e+02,  4.2068854e+02,  6.9700310e+01],
       [ 2.0307736e+02,  4.3157391e+02,  5.5881386e+01],
       [ 2.0984532e+02,  4.3901816e+02,  4.4501007e+01],
       [ 2.1638622e+02,  4.4423013e+02,  3.3814510e+01],
       [ 2.2412093e+02,  4.4748572e+02,  1.9677063e+01],
       [ 2.4004176e+02,  4.4880121e+02,  9.1065884e+00],
       [ 2.5755426e+02,  4.4281186e+02,  1.4542491e+01],
       [ 2.6927319e+02,  4.3538174e+02,  2.7989428e+01],
       [ 2.7811661e+02,  4.2689651e+02,  3.9248936e+01],
       [ 2.839803

In [15]:
type(results_l),len(results_l)

(list, 1)

In [10]:
results_l[0].keys()

dict_keys(['bbox', 'kps', 'det_score', 'landmark_3d_68', 'pose', 'landmark_2d_106', 'gender', 'age', 'embedding'])

In [11]:
results_l[0]['gender']

1

In [15]:
# here we will draw the bounding box of each detected face 
img_copy = img.copy()
gender_encode = ['Female','Male']
for res in results_l:
    x1,y1,x2,y2 = res['bbox'].astype(int)
    # draw a rectangle across the face
    cv2.rectangle(img_copy,(x1,y1),(x2,y2),(0,255,0),1)

    # key points
    kps = res['kps'].astype(int)
    for k1,k2 in kps:
        cv2.circle(img_copy,(k1,k2),2,(0,255,255),-1)

    # detection score
    score ='score: {}%'.format(int(res['det_score']*100))
    cv2.putText(img_copy,score,(x1,y1),cv2.FONT_HERSHEY_TRIPLEX,0.4,(226,121,15))           # for displaying the text for age though need to tweak a little bit.

    # age and gender- for male we get 1, for female 0
    gender = gender_encode[res['gender']]
    #age = res['age']
    #age_gender = f'{gender}::{age}'
    cv2.putText(img_copy,gender,(x1,y2),cv2.FONT_HERSHEY_DUPLEX,0.4,(255,255,255))          # for displaying the text for gender




cv2.imshow('bbox',img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()